export const POSTS_ACTIONS = {
  POSTS_REQUESTED: 'POSTS_REQUESTED',
  POSTS_RECEIVED: 'POSTS_RECEIVED',
  POSTS_FAILED: 'POSTS_FAILED'
};

export const MODAL_ACTIONS = { CHANGE_MODAL: 'CHANGE_MODAL' };

export const AUTH_ACTIONS = {
  AUTH_REQUESTED: 'AUTH_REQUESTED',
  AUTH_SUCCEED: 'AUTH_SUCCEED',
  AUTH_FAILED: 'AUTH_FAILED'
};
